# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('website', models.URLField()),
                ('services', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('logo', models.ImageField(blank=True, upload_to=b'printers', verbose_name='\u041b\u043e\u0433\u043e\u0442\u0438\u043f')),
            ],
            options={
                'verbose_name': '\u041f\u0435\u0447\u0430\u0442\u043d\u0438\u043a',
                'verbose_name_plural': '\u041f\u0435\u0447\u0430\u0442\u043d\u0438\u043a\u0438',
            },
        ),
    ]
