# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0002_printer_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, verbose_name='\u0422\u0435\u0433')),
            ],
        ),
        migrations.AlterField(
            model_name='printer',
            name='address',
            field=models.CharField(max_length=50, verbose_name='\u0410\u0434\u0440\u0435\u0441'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='lat',
            field=models.FloatField(verbose_name='\u0428\u0438\u0440\u043e\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='lon',
            field=models.FloatField(verbose_name='\u0414\u043e\u043b\u0433\u043e\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='services',
            field=models.CharField(max_length=50, verbose_name='\u0423\u0441\u043b\u0443\u0433\u0438'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='website',
            field=models.URLField(verbose_name='\u0412\u0435\u0431\u0441\u0430\u0439\u0442'),
        ),
        migrations.AddField(
            model_name='printer',
            name='categories',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='b2b.Categories'),
        ),
        migrations.AddField(
            model_name='printer',
            name='tags',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='b2b.Tags'),
        ),
    ]
