# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0003_auto_20170316_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f', 'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': '\u0422\u0435\u0433', 'verbose_name_plural': '\u0422\u0435\u0433\u0438'},
        ),
        migrations.AddField(
            model_name='tags',
            name='cat',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='b2b.Categories'),
        ),
    ]
