# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0004_auto_20170321_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='categories',
        ),
        migrations.AddField(
            model_name='printer',
            name='categories',
            field=models.ManyToManyField(to='b2b.Categories'),
        ),
        migrations.RemoveField(
            model_name='printer',
            name='tags',
        ),
        migrations.AddField(
            model_name='printer',
            name='tags',
            field=models.ManyToManyField(to='b2b.Tags'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='cat',
            field=models.ForeignKey(default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='b2b.Categories'),
        ),
    ]
