# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0005_auto_20170322_1543'),
        ('b2b', '0005_auto_20170322_1506'),
    ]

    operations = [
    ]
