# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('b2b', '0006_merge_20170322_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
