# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 15:52
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0007_printer_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='printer',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='printer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='id',
        ),
        migrations.AlterField(
            model_name='printer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
