# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0008_auto_20170324_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='logo',
            field=models.ImageField(blank=True, upload_to=b'.printers', verbose_name='\u041b\u043e\u0433\u043e\u0442\u0438\u043f'),
        ),
    ]
