# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0009_auto_20170328_0610'),
        ('b2b', '0009_auto_20170327_1802'),
    ]

    operations = [
    ]
