# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0010_merge_20170329_1542'),
        ('b2b', '0010_merge_20170330_1332'),
    ]

    operations = [
    ]
