# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0011_merge_20170330_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='middle_name',
            field=models.CharField(blank=True, default=b'', max_length=30, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
    ]
