# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0013_auto_20170412_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
