# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0014_printer_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='sub_expires',
            field=models.DateTimeField(null=True, verbose_name='\u041f\u043e\u0434\u043f\u0438\u0441\u043a\u0430 \u0438\u0441\u0442\u0435\u043a\u0430\u0435\u0442'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='subscribed',
            field=models.BooleanField(default=False, verbose_name='\u041f\u043e\u0434\u043f\u0438\u0441\u043a\u0430 \u0430\u043a\u0442\u0438\u0432\u043d\u0430'),
        ),
    ]
