# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0015_auto_20170414_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='categories',
            field=models.ManyToManyField(to='b2b.Categories', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='tags',
            field=models.ManyToManyField(to='b2b.Tags', verbose_name='\u0422\u0435\u0433\u0438'),
        ),
    ]
