# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0016_auto_20170417_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0438'),
        ),
    ]
