# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0020_auto_20170514_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='cat',
        ),
        migrations.AddField(
            model_name='tags',
            name='cat',
            field=models.ManyToManyField(to='b2b.Categories', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'),
        ),
    ]
