# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0004_auto_20170321_2150'),
        ('b2c', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='categories',
            field=models.ForeignKey(default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='b2b.Categories'),
        ),
        migrations.AddField(
            model_name='order',
            name='tags',
            field=models.ManyToManyField(to='b2b.Tags'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439'),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
    ]
