# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0009_auto_20170328_0610'),
        ('b2c', '0011_auto_20170325_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='responses',
            field=models.ManyToManyField(blank=True, related_name='order_responses', to='b2b.Printer'),
        ),
    ]
