# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2c', '0012_order_responses'),
        ('b2c', '0010_auto_20170324_1244'),
    ]

    operations = [
    ]
