# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Superuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciever', models.EmailField(max_length=254, verbose_name='Paypal \u0410\u043a\u043a\u0430\u0443\u043d\u0442')),
                ('amout', models.IntegerField(verbose_name='\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0438')),
            ],
            options={
                'verbose_name': 'Paypal',
                'verbose_name_plural': 'Paypal',
            },
        ),
    ]
