# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 19:23
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='short_text',
            field=redactor.fields.RedactorField(default=b'', verbose_name='Text'),
        ),
    ]
