# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_entry_short_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': '\u0420\u0435\u0434\u0430\u043a\u0442\u043e\u0440', 'verbose_name_plural': '\u0420\u0435\u0434\u0430\u043a\u0442\u043e\u0440'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(choices=[(b'\xd0\x93\xd0\xbb\xd0\xb0\xd0\xb2\xd0\xbd\xd0\xb0\xd1\x8f', b'\xd0\x93\xd0\xbb\xd0\xb0\xd0\xb2\xd0\xbd\xd0\xb0\xd1\x8f'), (b'about', b'\xd0\x9e \xd0\xbd\xd0\xb0\xd1\x81'), (b'printing1', b'\xd0\x9e \xd0\xbf\xd0\xb5\xd1\x87\xd0\xb0\xd1\x82\xd0\xb8 1'), (b'printing2', b'\xd0\x9e \xd0\xbf\xd0\xb5\xd1\x87\xd0\xb0\xd1\x82\xd0\xb8 2'), (b'printing3', b'\xd0\x9e \xd0\xbf\xd0\xb5\xd1\x87\xd0\xb0\xd1\x82\xd0\xb8 3')], max_length=50, unique=True),
        ),
    ]
