# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20170328_0604'),
        ('content', '0004_auto_20170323_1608'),
        ('content', '0004_auto_20170328_0610'),
    ]

    operations = [
    ]
